# Organização dos dados

In [1]:
import pandas as pd
import numpy as np

## Dados de classificação

In [10]:
# Dados históricos

dic_classificacao = {
    'Pessoa': ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
    'Altura (m)': [1.70, 1.65, 1.80, 1.75, 1.60, 1.85, 1.68],
    'Peso (kg)': [70, 90, 80, 95, 50, 110, 68],
    'Classe': [
        'Atleta',      # A: IMC ~24.22
        'Não Atleta',  # B: IMC ~33.06
        'Atleta',      # C: IMC ~24.69
        'Não Atleta',  # D: IMC ~31.02
        'Atleta',      # E: IMC ~19.53
        'Não Atleta',  # F: IMC ~32.15
        'Atleta'       # G: IMC ~24.07
    ]
}

df_historicos = pd.DataFrame(dic_classificacao)


# Novo exemplo

dic_novo_exemplo = {
    'Pessoa':['H'],
    'Altura (m)':[1.72],
    'Peso (kg)': [72],
    'Classe': [np.nan]
}

df_novo = pd.DataFrame(dic_novo_exemplo)

In [3]:
# Históricos

df_historicos

  Pessoa  Altura (m)  Peso (kg)      Classe
0      A        1.70         70      Atleta
1      B        1.65         90  Não Atleta
2      C        1.80         80      Atleta
3      D        1.75         95  Não Atleta
4      E        1.60         50      Atleta
5      F        1.85        110  Não Atleta
6      G        1.68         68      Atleta

In [4]:
# Dados novos

df_novo

  Pessoa  Altura (m)  Peso (kg)  Classe
0      H        1.72         72     NaN

In [5]:
# Salvando

df_historicos.to_csv('data/df_historicos_classificacao',index=False)
df_novo.to_csv('data/df_novo_classificacao',index=False)

## Dados de regressão

In [6]:
# Dados históricos

dic_regressao = {
    'Pessoa': ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
    'Altura (m)': [1.70, 1.65, 1.80, 1.75, 1.60, 1.85, 1.68],
    'Peso (kg)': [70, 90, 80, 95, 50, 110, 68],
    'TempoCorrida(min)': [
        28.0,  # A - corredor recreativo
        45.5,  # B - corredor lento
        22.0,  # C - corredor intermediário
        55.0,  # D - muito lento (caminhada/corrida leve)
        20.0,  # E - corredor rápido
        50.0,  # F - lento
        25.5   # G - corredor intermediário
    ]
}

df_historicos = pd.DataFrame(dic_regressao)


# Novo exemplo

dic_novo_exemplo = {
    'Pessoa': ['H'],
    'Altura (m)': [1.72],
    'Peso (kg)': [72],
    'TempoCorrida(min)': [np.nan]  # valor desconhecido a ser previsto
}

df_novo = pd.DataFrame(dic_novo_exemplo)

In [7]:
# Históricos

df_historicos

  Pessoa  Altura (m)  Peso (kg)  TempoCorrida(min)
0      A        1.70         70               28.0
1      B        1.65         90               45.5
2      C        1.80         80               22.0
3      D        1.75         95               55.0
4      E        1.60         50               20.0
5      F        1.85        110               50.0
6      G        1.68         68               25.5

In [8]:
# Dados novos

df_novo

  Pessoa  Altura (m)  Peso (kg)  TempoCorrida(min)
0      H        1.72         72                NaN

In [9]:
# Salvando

df_historicos.to_csv('data/df_historicos_regressao',index=False)
df_novo.to_csv('data/df_novo_regressao',index=False)